# Example Site settings

#google_analytics: UA-NNNNNNNN-N

title: "Moon's page"
baseurl: "/"
url: "https://monster-moon.github.io"

header_pages:
 - index.md
 - about.md

footer: 'follow me on <a href="https://github.com/Monster-Moon/">Github</a>'

# style: light # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
