# Example Site settings

#google_analytics: UA-NNNNNNNN-N

title: "Moon's page"
baseurl: "/"
url: "https://monster-moon.github.io" 
description: "My brief ideas and experiences"

header_pages:
 - index.md
 - posts.md
 - about.md

footer: 'Email me to <a href=mailto:msj5589@gmail.com>Here</a>, or follow me on <a href="https://github.com/Monster-Moon/">Github</a>'

# style: light # dark (default) or light
# listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
